### ISSUE TITLE
Bitwise And/Or , may need assert and assume

### ISSUE THREAD

**Issue by kroeckx** [fmlab-iis/gcc2cryptoline#1]
Hi,

I was trying to look at how this works. The README.md gave fe51_mul as an example, so I tried that too. When I then try to verify the file I get, it fails. So I started comparing the files. The fe51_mul_auto.cl file contains:
```
(* _112 = _31 & 18446744073709551615; *)
(* Note: high part 0x0@uint64 = 0x00000000000000 *)
(* Note: high part 0x0@uint64 = 0b00000000000000000000000000000000000000000000000000000000000000 *)
(* Note: low part 0xffffffffffffffff@uint64 = 0xffffffffffffffff *)
(* Note: low part 0xffffffffffffffff@uint64 = 0b1111111111111111111111111111111111111111111111111111111111111111 *)
mov value_lo 0xffffffffffffffff@uint64;
mov value_hi 0x0@uint64;
join value value_hi value_lo;
and uint128 v112 v31 value;
```

The fe51_mul_tuned.cl file contains:
```
(* _112 = _31 & 18446744073709551615; *)
(* Note: high part 0 = 0x0000000000000000 *)
(* Note: high part 0 = 0b00000000000000000000000000000000000000000000000000000000000000 *)
(* Note: low part 18446744073709551615 = 0xFFFFFFFFFFFFFFFF *)
(* Note: low part 18446744073709551615 = 0b1111111111111111111111111111111111111111111111111111111111111111 *)
(* TODO: check heuristic or self translate *)
mov value_lo 0xFFFFFFFFFFFFFFFF@uint64;
mov value_hi 0x0000000000000000@uint64;
join value value_hi value_lo;
and uint128 v112 v31 value;

assert true && v112 = v31;
assume v112 = v31 && true;
```

And my file contains:
```
/* _112 = _31 & 18446744073709551615; */
/* TODO: Bitwise And/Or , may need assert and assume */
and uint128 v112 v31 0xffffffffffffffff@uint128;
```

Every time that TODO is mentioned, an assert/assume is the tuned file. Is that assert/assume needed to make the verify possible? Are there plans to make it auto generate it?

**Comment by bowyaw** [comment]
Hi,

The tools are not fully automatic unfortunately. TODO gives us hint for manual modification.

Our tool has two verification engines: algebraic and logic. The algebraic engine proves algebraic properties. The logic engine proves logical properties. These two engines do not talk to each other directly. We have to pass information between them with assert/assume. In

`and uint128 v112 v31 0xffffffffffffffff@uint128;`

The logical `and` operation is used. The logic engine easily proves

`assert true && v112 = v31;`

And we pass the equality to the algebraic engine by

`assume v112 = v31 && true;`

Note the algebraic and logical properties are at the left and right of `&&` respectively. These assert/assume are needed to make verification possible.

In the above case, the modification is simple. But non-trivial modification are needed in general. You can find more of them in examples. Currently, we don't know how to add assert/assume in general cases. We don't feel it worth the effort to handle special cases due to limited resources. There is no short-term plan to generate assert/assume automatically. I'm afraid human intervention is still needed.
